version: "3.7"

services:
  db:
    image: mysql:5.7.27
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: task
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
